//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////
//                                                          //
// This SystemC file has been generated by the verilog2sc    //
// tool.                                                    //
// Contact help@edautils.com  for support/info.//
//                                                          //
//                                                          //
//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////
//
//
//
// Generated by : apache on 1/19/21 2:55 PM
//
//
#include "systemc.h" 
SC_MODULE(RealGCD) 
{
    sc_in_clk clock;
    sc_in< sc_logic > reset;
    sc_out< sc_logic > io_in_ready;
    sc_in< sc_logic > io_in_valid;
    sc_in< sc_lv< 16 > > io_in_bits_a;
    sc_in< sc_lv< 16 > > io_in_bits_b;
    sc_out< sc_logic > io_out_valid;
    sc_out< sc_lv< 16 > > io_out_bits;
    sc_signal< sc_lv< 16 > > a;
    sc_signal< sc_lv< 16 > > b;
    sc_signal< sc_logic > busy;
    sc_signal< sc_logic > allow_enter;
    sc_signal< sc_logic > gt;
    sc_signal< sc_lv< 16 > > sub;
    void func_allow_enter();
    void func_gt();
    void func_sub();
    void func_io_in_ready();
    void func_io_out_valid();
    void func_io_out_bits();
    void func_a_b_busy();
    SC_CTOR( RealGCD )
    {
        SC_THREAD( func_allow_enter );
        sensitive << io_in_valid << busy;
        SC_THREAD( func_gt );
        sensitive << a << b;
        SC_THREAD( func_sub );
        sensitive << b << a;
        SC_THREAD( func_io_in_ready );
        sensitive << busy;
        SC_THREAD( func_io_out_valid );
        sensitive << b << busy;
        SC_THREAD( func_io_out_bits );
        sensitive << a;
        SC_THREAD( func_a_b_busy );
        sensitive << clock.pos();
    }
};

