//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////
//                                                          //
// This SystemC file has been generated by the verilog2sc    //
// tool.                                                    //
// Contact help@edautils.com  for support/info.//
//                                                          //
//                                                          //
//////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////
//
//
//
// Generated by : apache on 1/19/21 2:55 PM
//
//
#include "systemc.h" 
SC_MODULE(RealGCD) 
{
    sc_in_clk clock;
    sc_in< sc_logic > reset;
    sc_out< sc_logic > io_in_ready;
    sc_in< sc_logic > io_in_valid;
    sc_in< sc_lv< 16 > > io_in_bits_a;
    sc_in< sc_lv< 16 > > io_in_bits_b;
    sc_out< sc_logic > io_out_valid;
    sc_out< sc_lv< 16 > > io_out_bits;
    sc_signal< sc_lv< 16 > > a;
    sc_signal< sc_lv< 16 > > b;
    sc_signal< sc_logic > busy;
    sc_signal< sc_logic > allow_enter;
    sc_signal< sc_logic > gt;
    sc_signal< sc_lv< 16 > > sub;
    void assign_stmt_at_line_17_1506083063();
    void assign_stmt_at_line_18_829217329();
    void assign_stmt_at_line_19_1343293809();
    void assign_stmt_at_line_20_399683701();
    void assign_stmt_at_line_21_1717688512();
    void assign_stmt_at_line_22_822815599();
    void always_stmt_at_line_24_1762260670();
    SC_CTOR( RealGCD )
    {
        SC_THREAD( assign_stmt_at_line_17_1506083063 );
        sensitive << io_in_valid << busy;
        SC_THREAD( assign_stmt_at_line_18_829217329 );
        sensitive << a << b;
        SC_THREAD( assign_stmt_at_line_19_1343293809 );
        sensitive << b << a;
        SC_THREAD( assign_stmt_at_line_20_399683701 );
        sensitive << busy;
        SC_THREAD( assign_stmt_at_line_21_1717688512 );
        sensitive << b << busy;
        SC_THREAD( assign_stmt_at_line_22_822815599 );
        sensitive << a;
        SC_THREAD( always_stmt_at_line_24_1762260670 );
        sensitive << clock.pos();
    }
};

